# Generated by Django 2.1 on 2019-05-16 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0002_auto_20190504_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
