# Generated by Django 2.0.3 on 2019-05-22 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0003_lecturer_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='upload',
        ),
    ]
