# Generated by Django 2.1 on 2019-05-22 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0004_remove_lecturer_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
