# Generated by Django 2.1 on 2019-05-27 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0008_auto_20190528_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='id',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
