# Generated by Django 2.1 on 2019-05-27 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0009_auto_20190528_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='id',
            field=models.AutoField(auto_created=True, default=46, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
