# Generated by Django 2.1 on 2019-05-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0012_auto_20190528_0613'),
        ('lecturer', '0006_remove_lecturer_upload'),
    ]

    operations = [
    ]
