# Generated by Django 2.1 on 2019-05-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20190516_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemajor',
            name='CourseCode',
            field=models.CharField(default='XENG01', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseCode',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseName',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='unit',
            name='UnitCode',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='UnitName',
            field=models.CharField(max_length=400),
        ),
        migrations.RemoveField(
            model_name='coursemajor',
            name='CourseName',
        ),
        migrations.AlterUniqueTogether(
            name='coursemajor',
            unique_together={('CourseCode', 'Field')},
        ),
    ]
