# Generated by Django 2.1 on 2019-05-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20190516_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='PreRequisite',
            field=models.BinaryField(),
        ),
    ]
