# Generated by Django 2.1 on 2019-05-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20190518_0942'),
        ('student', '0010_auto_20190517_2126'),
    ]

    operations = [
    ]
