# Generated by Django 2.0.3 on 2019-05-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20190518_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='Semester',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
            preserve_default=False,
        ),
    ]
