# Generated by Django 2.0.3 on 2019-05-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_unit_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='Year',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
            preserve_default=False,
        ),
    ]
