# Generated by Django 2.0.3 on 2019-05-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_coursemajor_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='Points',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='coursemajor',
            name='Semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2)]),
        ),
        migrations.AlterField(
            model_name='coursemajor',
            name='Year',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='Semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2)]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='Year',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
