# Generated by Django 2.0.3 on 2019-05-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20190524_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterunit',
            name='Field',
            field=models.CharField(default='Chemical Engineering ', max_length=400),
        ),
    ]
