# Generated by Django 2.1 on 2019-05-26 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20190522_1924'),
        ('student', '0018_auto_20190524_2158'),
    ]

    operations = [
    ]
